CREATE DATABASE IF NOT EXISTS CompuShop;

USE CompuShop;

CREATE TABLE IF NOT EXISTS products (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    picture VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    info TEXT,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
